### ISSUE TITLE
Multiples Datasources on the same sql-exporter

### ISSUE THREAD

**Issue by MRTRALHA** [burningalchemist/sql_exporter#112]
Hello,

I've read the config but haven't found a reference to this.

is it possible in the same sql-exporter service to have several datasources with the same/different collectors?

My ideia is that I need the database size of several databases that are in different ms-sql servers.

Can the data source be in the collectors files and we just say in the sql_exporter.yml to use the collectors files? Or is it support in any other way?

I've tried adding a new datasource_name but it tells me that it is already defined... even a new target didn't work.

best regards,

MRT

**Comment by burningalchemist** [comment]
Hi @MRTRALHA,

Although it's not documented at the moment, I'd try something similar to [this](https://github.com/burningalchemist/sql_exporter/issues/37#issuecomment-849135820) solution.

In other words, we want to use a configured `jobs` construct instead of `target`.
I'd suggest trying it out.

Overall, we don't want to over-complicate the exporter given its small size. But hope it helps.

Cheers,
Sergei
