### ISSUE TITLE
Not supporting special characters on passwords for the connection string 

### ISSUE THREAD

**Issue by ocrivador** [burningalchemist/sql_exporter#241]
Something minor I noted post update.
After updating to the latest version, 0.10.1 (from 0.8.4), noted that the exporter is not reporting metrics due to a special character on the password (#), this password was generated through keepass long ago and was working for the previous version.

1. Having a special character password (this case with # for example, PWDPART1#PWDPART2) and having sql_exporter v0.8.4.0 working;
2. Update sql-exporter to version 0.10.1;
3. Access the metrics endpoint: `curl http://127.0.0.1:9399/metrics`
4. See error:
`No metrics gathered, [from Gatherer #1] invalid port ":PWDPART1" after host`

Expected behavior:
SQL exporter to return metrics instead of an error;

Additional context:
Using SQL_Exporter to extract a couple of metrics from a specific table, the query on its own works fine before and after the update;

Workaround:
Other special characters can be used to ensure a safe password, but not '#'

**Comment by burningalchemist** [comment]
Hey @ocrivador, thanks for reporting the issue! :) It seems to originate in the upstream dependency, I'll investigate and come up with the fix. 👍

**Comment by burningalchemist** [comment]
Hey @ocrivador, as I mentioned before, the issue comes from the `dburl` dependency, which was adopted since v0.9. I'll drop a reference link here: https://github.com/xo/dburl/issues/3

Overall, the limitations described are applied to sql_exporter too.

Interestingly, in the linked issue it's MSSQL driver having a problem with `#`. Could you please share what's the driver on your end?

If so, we can two options:
- warn users about the password limitations (since we parse the DSN, the `#` sign is likely a reserved character);
- we can explicitly encode the # character.

As far as I see the problem at the moment, URL fragments are being parsed (which is a valid point net/url package), however I haven't seen DSNs so far where fragments mean something *(but I might be wrong). In this case, if we could avoid parsing fragments, then we don't have an issue too.

Given that it happens in the upstream, I don't see any immediate fix besides the options posted above.
