### ISSUE TITLE
Add support for version specific queries

### ISSUE THREAD

**Issue by redbaron** [burningalchemist/sql_exporter#272]
**Is your feature request related to a problem? Please describe.**
PostgreSQL database changes the way it represents stats based on version.  Reconfiguring sql_exporter as DB version changes with new set of queries can be unpractical. Ideally sql_exporter should be able to select which queries to run dynamically.

**Describe the solution you'd like**
Each query can provide optional version constraint as a semver string. Each database connection should have optional field with a query how to extract DB version as there seems to be no standard way to do that across all databases.

sql_exporter upon connection queries DB version and then checks each configured query against it. If query didn't specify version it is accepted by default, otherwise semver version check is performed. 

**Additional context**

Use case: 
- https://github.com/prometheus-community/postgres_exporter/issues/502
- https://github.com/prometheus-community/postgres_exporter/pull/553

**Comment by burningalchemist** [comment]
Hi @redbaron, thank you for your suggestion!

Since `sql_exporter` is a db-agnostic solution, it's undesired that we add any special query handling for particular databases (in your case, `PostgreSQL`) to address version-related object differences. In this regard, query management is also a part of user responsibility, and I believe the config file can be templated externally.

In the meantime, it seems the issue with column names has been [addressed](https://github.com/prometheus-community/postgres_exporter/commit/f9277b04b7f614a03a4ca70194abe2045f17c36a) in `postgres_exporter`.

**Comment by burningalchemist** [comment]
Hey @redbaron, I assumed you need `pg_stat_statements` extension metrics which seem to be implemented in `postgres_exporter` as a separate collector. But if you need to execute custom queries against PostgreSQL-specific tables, `sql_exporter`, indeed, might come in handy. However, version-specific queries feature isn't considered a priority for now, so there's no ETA I can promise.
