### ISSUE TITLE
Releases built with incorrect Go toolchain

### ISSUE THREAD

**Issue by hhromic** [burningalchemist/sql_exporter#336]
**Describe the bug**
According to the release pages, the last two versions (v0.12.2 and v0.12.3) are supposedly built with Go v1.21.1.

> Precompiled binaries are built with Go v1.21.1.

However, both binaries report that they were built with Go v1.20.8:
```
# sql_exporter --version
sql_exporter, version 0.12.2 (branch: HEAD, revision: 588b42d329deb17d86b50de94c52bc3dca264b0c)
  build user:       root@4d35747bd17e
  build date:       20230915-10:31:21
  go version:       go1.20.8
  platform:         linux/amd64
  tags:             netgo

# sql_exporter --version
sql_exporter, version 0.12.3 (branch: HEAD, revision: d25cd797ff6b4daa53a5b9cc29c4aee3c998cb9f)
  build user:       root@3c5818fec6b5
  build date:       20230920-16:19:10
  go version:       go1.20.8
  platform:         linux/amd64
  tags:             netgo
```

**To Reproduce**
1. Download the binary distribution for either v0.12.2 or v0.12.3
2. Run `sql_exporter --version`
3. Observe the reported `go version`

**Comment by burningalchemist** [comment]
Hey @hhromic, thanks for reporting the issue. The golang version is, indeed, managed in[ .promu.yml](https://github.com/burningalchemist/sql_exporter/blob/53330782ae23c54bb45c4fdb9053b7a83785aed0/.promu.yml#L3). And even though PRs are built with `v1.21.x`, release binaries are built with `v1.20.x`. So the root cause is I forgot to update `.promu.yml`.

I'll update the release page so there's no confusion anymore. Next release will use go `v1.21.x`.

**Comment by hhromic** [comment]
Ha, I knew it would be a small oversight but wasn't sure exactly where.
Happy to help! And cheers for the prompt reply!
