### ISSUE TITLE
SIGHUP config reload

### ISSUE THREAD

**Issue by reubano** [burningalchemist/sql_exporter#543]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when I need to reload sql_exporter without making an HTTP request 

**Describe the solution you'd like**

SIGHUP based config reload (similar to [Prometheus](https://github.com/prometheus/prometheus/issues/1572)). E.g., `killall -HUP sql_exporter`

**Describe alternatives you've considered**

`-web.enable-reload`. But since I'm running sql_exporter in an unexposed Azure container, I can't make an HTTP call to the reload endpoint. I can, however, run `az container exec` which would allow me to call `killall -HUP`.

**Additional context**

HTTP flags are considered a [security concern in Prometheus](https://prometheus.io/docs/operating/security/#prometheus), so a SIGHUP based sql_exporter reload would likewise be considered more secure than an HTTP flag.

**Comment by reubano** [comment]
FYI, turns out I am able to curl localhost via the nginx container. This would still be a nice feature though for the security benefits.

**Comment by burningalchemist** [comment]
Hi @reubano, there are no security concerns specifically for this specific endpoint (I also previously elaborated on that front before, since `sql_exporter` is not Prometheus), as `/reload` endpoint is idempotent and read-only, there are no mutations involved.

Also, sql_exporter is not supposed to run in public networks, similar to how databases usually locate within private networks.

But yeah, I'll put SIGHUP reload feature in the list of improvements, when I find some free time. It probably won't take much time.

Thanks for your contributions as always! :)

**Comment by reubano** [comment]
@burningalchemist thanks! Since I confirmed that I can curl to localhost there's no urgency on my end. I'll report back once I have everything working.

**Comment by burningalchemist** [comment]
Hey @reubano, JFYI, I've merged the SIGHUP support, and it should appear in the next release. 🚀
