### ISSUE TITLE
Connection Closure

### ISSUE THREAD

**Issue by jesus-velez** [burningalchemist/sql_exporter#66]
I was not sure where to ask this, if this is not the right place please point me in the right direction. Firstly, thank you for maintaining this project. My question is regarding connection closure after the query is executed, it looks like connections are maintained and queries are executed every scrape. If I wanted to end the query after the query is executed; would this be possible? I use the exporter to get information out of databases and also test connectivity.

**Comment by jesus-velez** [comment]
I found [#27 ](https://github.com/burningalchemist/sql_exporter/issues/27#issuecomment-841700029) would this change the behavior of keeping the connection open? I basically use queries to get database health or information while also testing the the VIP works. I do this on MySQL, SQLServer and postgres.

**Comment by burningalchemist** [comment]
Hi @jesus-velez! I don't think disabling ping would help in your case. The issue reporters of #27 had was due to the warehouse being in active state (instead of being suspended) and associated charges. Say, Snowflake specific things.

As far as I got, you would like to disconnect each time after receiving a response. Please correct me if I understood it wrong. The thing managing connections with a connection pool (with active/idle connections) is more resource wise efficient than creating a new connection each time.

I can suggest few options:
- play around with `max_connections`, `max_idle_connections and `max_connection_lifetime` (infinite if unset).
- it might be easier to develop a dedicated program or script to perform it in a straightforward way. Or you can just fork this project and slightly adjust the logic.

Let me know if you have any questions, I'm happy to assist. Also if you could describe the problem you're originally solving, I could probably think about it too. :)

**Comment by burningalchemist** [comment]
Thanks for the details. :+1:

Yeah, the settings above should suffice. You can additionally set `max_connections` to 1 - this will limit the maximum number of open connections to the database.

For opened sessions you can also double check the session manager on the database side to make sure there's no opened connections.

**Comment by jesus-velez** [comment]
I have this opened while I test, will close it as soon as I am done. Again thanks for the help.

**Comment by burningalchemist** [comment]
Yup! Let me know if anything, happy to assist. 🙂👍

**Comment by jesus-velez** [comment]
After testing this it does achieve the connect disconnect that I was looking for, but I lost some features along the way. It used to log when a host was not reachable for example:

```
Nov 15 14:10:00 promtheus-tst00 sql_exporter[16415]: * [from Gatherer #1] [job="sql-exporter-mssql", target="host01:1433", collector="mssql_standard", query="mssql_synchronization_health"] prepare query failed: lookup host01 on 10.5.25.196:53: no such host
Nov 15 14:10:00 promtheus-tst00 sql_exporter[16415]: * [from Gatherer #1] [job="sql-exporter-mssql", target="host01:1433", collector="mssql_standard", query="mssql_job_duration"] prepare query failed: lookup host01 on 10.5.25.196:53: no such host
Nov 15 14:10:00 promtheus-tst00 sql_exporter[16415]: * [from Gatherer #1] [job="sql-exporter-mssql", target="host01:1433", collector="mssql_standard", query="mssql_local_time_seconds"] prepare query failed: lookup host01 on 10.5.25.196:53: no such host
Nov 15 14:10:00 promtheus-tst00 sql_exporter[16415]: * [from Gatherer #1] [job="sql-exporter-mssql", target="host01:1433", collector="mssql_standard", query="mssql_quorum_state"] prepare query failed: lookup host01 on 10.5.25.196:53: no such host
```

Is now being reported as 1 on the metrics instead of 0. Any idea on what might be causing this?

```
up{env="mssql-nonprod",instance="host01:1433",job="sql-exporter-mssql"} 1
```

**Comment by jesus-velez** [comment]
I think I figured that out immediately after posting this its the ping = false configuration.

**Comment by burningalchemist** [comment]
Hi @jesus-velez! I'll take a look, it doesn't sound good to me. Thanks for the feedback! 🙂

Did you achieve the goal without setting ping value to false?

**Comment by jesus-velez** [comment]
I did!

```
up{env="mssql-nonprod",instance="host01:1433",job="sql-exporter-mssql"} 0
```

**Comment by burningalchemist** [comment]
Perfect!

Ok, I'll create a separate issue for the ping misbehaviour. 👍

**Comment by jesus-velez** [comment]
Working great so far. Thanks for all the help.
